// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(isAlphabetical("alex", "bob") == true );
    REQUIRE(isAlphabetical("Alex", "Bob") == true);
    REQUIRE(isAlphabetical("alex", "alexander") == true );
    REQUIRE(isAlphabetical("alex", "alex") == true);
    REQUIRE(isAlphabetical("Bob", "Bob") == true);
    REQUIRE(isAlphabetical("bob", "alexa") == false);
    REQUIRE(isAlphabetical("zena", "alexa") == false);
    REQUIRE(isAlphabetical("aaron", "azuma") == true);
    REQUIRE(isAlphabetical("azuma", "aaron") == false);

}

